import {
  DealPriority,
  SponsorshipStage,
} from "@/features/sponsorship/enums/sponsorship"
import type { Deal } from "@/features/sponsorship/types/sponsorship"

export interface MonthlyRevenueDatum {
  month: string
  revenue: number
  deals: number
}

export const SEED_DEALS: Deal[] = [
  {
    id: 1,
    brand: "Lumi Beauty",
    logo: "LB",
    logoColor: "#E8402A",
    value: 7500,
    stage: SponsorshipStage.LEAD,
    category: "Beauty",
    contact: "Sarah Kim",
    email: "sarah@lumibauty.co",
    deadline: "Jul 15",
    notes: "Inbound inquiry via Instagram DM",
    priority: DealPriority.HIGH,
    added: "Jun 5",
    month: 6,
  },
  {
    id: 2,
    brand: "Arc Wellness",
    logo: "AW",
    logoColor: "#111111",
    value: 4200,
    stage: SponsorshipStage.LEAD,
    category: "Health",
    contact: "Tom Richards",
    email: "tom@arcwellness.com",
    deadline: "Jul 20",
    notes: "Referral from Meridian deal",
    priority: DealPriority.MEDIUM,
    added: "Jun 7",
    month: 6,
  },
  {
    id: 3,
    brand: "Skyline Apparel",
    logo: "SA",
    logoColor: "#E8402A",
    value: 6000,
    stage: SponsorshipStage.OUTREACH,
    category: "Fashion",
    contact: "Maya Patel",
    email: "maya@skylineapp.com",
    deadline: "Jun 30",
    notes: "Sent pitch deck + rate card",
    priority: DealPriority.HIGH,
    added: "May 28",
    month: 5,
  },
  {
    id: 4,
    brand: "Rover Tech",
    logo: "RT",
    logoColor: "#111111",
    value: 9800,
    stage: SponsorshipStage.OUTREACH,
    category: "Technology",
    contact: "Jake Osei",
    email: "jake@rovertech.io",
    deadline: "Jul 10",
    notes: "Follow-up call booked Jun 12",
    priority: DealPriority.HIGH,
    added: "Jun 1",
    month: 6,
  },
  {
    id: 5,
    brand: "Drift Coffee",
    logo: "DC",
    logoColor: "#E8402A",
    value: 2500,
    stage: SponsorshipStage.NEGOTIATION,
    category: "Food & Bev",
    contact: "Ava Liu",
    email: "ava@driftcoffee.co",
    deadline: "Jun 25",
    notes: "Counter-offer received — $2,200",
    priority: DealPriority.MEDIUM,
    added: "May 20",
    month: 5,
  },
  {
    id: 6,
    brand: "Nomad Finance",
    logo: "NF",
    logoColor: "#111111",
    value: 11500,
    stage: SponsorshipStage.NEGOTIATION,
    category: "Finance",
    contact: "Carlos Reyes",
    email: "carlos@nomadfi.com",
    deadline: "Jun 28",
    notes: "Contract review with legal",
    priority: DealPriority.HIGH,
    added: "May 15",
    month: 5,
  },
  {
    id: 7,
    brand: "Glow Republic",
    logo: "GR",
    logoColor: "#E8402A",
    value: 8500,
    stage: SponsorshipStage.SIGNED,
    category: "Beauty",
    contact: "Nisha Sharma",
    email: "nisha@glowrepublic.co",
    deadline: "Jul 5",
    notes: "Brief received — 3 Reels due Jul",
    priority: DealPriority.HIGH,
    added: "May 10",
    month: 5,
  },
  {
    id: 8,
    brand: "Pulse Tech",
    logo: "PT",
    logoColor: "#111111",
    value: 5400,
    stage: SponsorshipStage.SIGNED,
    category: "Technology",
    contact: "Daniel Park",
    email: "dan@pulsetech.com",
    deadline: "Jun 24",
    notes: "Integration video + 2 stories",
    priority: DealPriority.MEDIUM,
    added: "Jun 2",
    month: 6,
  },
  {
    id: 9,
    brand: "Meridian Health",
    logo: "MH",
    logoColor: "#E8402A",
    value: 9200,
    stage: SponsorshipStage.PAID,
    category: "Health",
    contact: "Priya Anand",
    email: "priya@meridian.co",
    deadline: "Done",
    notes: "Campaign completed — invoice paid",
    priority: DealPriority.LOW,
    added: "Apr 20",
    month: 4,
  },
  {
    id: 10,
    brand: "Vibe Studio",
    logo: "VS",
    logoColor: "#111111",
    value: 3100,
    stage: SponsorshipStage.PAID,
    category: "Lifestyle",
    contact: "Owen Clarke",
    email: "owen@vibestudio.io",
    deadline: "Done",
    notes: "4 deliverables approved",
    priority: DealPriority.LOW,
    added: "Apr 8",
    month: 4,
  },
  {
    id: 11,
    brand: "Neon Labs",
    logo: "NL",
    logoColor: "#E8402A",
    value: 6800,
    stage: SponsorshipStage.PAID,
    category: "Technology",
    contact: "Wei Zhang",
    email: "wei@neonlabs.io",
    deadline: "Done",
    notes: "YouTube integration done",
    priority: DealPriority.LOW,
    added: "Mar 12",
    month: 3,
  },
  {
    id: 12,
    brand: "Fresh Press",
    logo: "FP",
    logoColor: "#111111",
    value: 2800,
    stage: SponsorshipStage.PAID,
    category: "Food & Bev",
    contact: "Lila Moreau",
    email: "lila@freshpress.co",
    deadline: "Done",
    notes: "2 story posts delivered",
    priority: DealPriority.LOW,
    added: "Feb 5",
    month: 2,
  },
]

export const MONTHLY_DATA: MonthlyRevenueDatum[] = [
  { month: "Jan", revenue: 0, deals: 0 },
  { month: "Feb", revenue: 2800, deals: 1 },
  { month: "Mar", revenue: 6800, deals: 1 },
  { month: "Apr", revenue: 12300, deals: 2 },
  { month: "May", revenue: 8200, deals: 3 },
  { month: "Jun", revenue: 5400, deals: 2 },
]
